title: AD Conference Deadlines # (Maintained by @daniel-bogdoll)
# email: daniel.bogdoll@rwth-aachen.de
description: Countdowns to AD-related conference deadlines
author: Daniel Bogdoll

domain: ""
baseurl: "https://daniel-bogdoll.github.io/ad-deadlines/"

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: abhshkdz
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
