title: AD Conference Deadlines # (Maintained by @daniel-bogdoll)
# email: daniel.bogdoll@rwth-aachen.de
description: Countdowns to AD-related conference deadlines
author: Daniel Bogdoll

domain: "ad-deadlines.com"
baseurl: ""

twitter_username: BogdollDaniel
twitter_hashtag: machinelearning
github_username: daniel-bogdoll
github_repo: ad-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
