---
- name: INSTICC
  url: https://portal.insticc.org/
- name: SAI
  url: https://saiconference.com/Conferences
- name: IEEE
  url: https://www.ieee.org/conferences/
- name: ACM
  url: https://www.acm.org/conferences
- name: CVF
  url: https://www.thecvf.com/
