# This is a basic workflow to help you get started with Actions

name: On Push Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  push:
    branches: [ gh-pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/utils/process.py
      shell: sh
